# CONFIGURACIÓN GENERAL DE LA APLICACIÓN
# Nombre identificativo del microservicio en el ecosistema Spring.
spring.application.name=Investment_Tracking

# PERSISTENCIA Y CONEXIÓN A DATOS (MARIADB)
# URL de conexión. Incluye parámetro para crear la base de datos si no existe.
spring.datasource.url=jdbc:mariadb://localhost:3306/invest_db?createDatabaseIfNotExist=true
# Driver específico para la comunicación con el motor MariaDB.
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# Credenciales de acceso al servidor de base de datos local.
spring.datasource.username=root
spring.datasource.password=root

# CONFIGURACIÓN DE JPA / HIBERNATE
# Modo de inicialización: 'always' asegura que se ejecuten scripts de carga si existen.
spring.sql.init.mode=always
# Sincroniza el modelo de clases Java con las tablas de MariaDB automáticamente.
spring.jpa.hibernate.ddl-auto=update
# Define el lenguaje SQL específico (Dialecto) para MariaDB.
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
# Mejora el rendimiento cerrando la sesión de BD inmediatamente tras terminar el Service.
spring.jpa.open-in-view=false

# LOGGING Y TRAZABILIDAD (DEBUG MODE)
# Permite rastrear errores en la validación de Tokens JWT y filtros de acceso.
logging.level.org.springframework.security=DEBUG
# Muestra las consultas SQL reales que Spring envía a MariaDB en la consola.
logging.level.org.hibernate.SQL=DEBUG
# Muestra los valores exactos (parámetros) que se insertan en las consultas SQL.
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE